// Code generated by mockery v2.51.1. DO NOT EDIT.

package remote_svc_provider_mocks

import (
	git "terraform-provider-tfmigrate/internal/util/vcs/git"

	mock "github.com/stretchr/testify/mock"
)

// MockGithubSvcProvider is an autogenerated mock type for the GithubSvcProvider type
type MockGithubSvcProvider struct {
	mock.Mock
}

type MockGithubSvcProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGithubSvcProvider) EXPECT() *MockGithubSvcProvider_Expecter {
	return &MockGithubSvcProvider_Expecter{mock: &_m.Mock}
}

// CreatePullRequest provides a mock function with given fields: params
func (_m *MockGithubSvcProvider) CreatePullRequest(params git.PullRequestParams) (string, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(git.PullRequestParams) (string, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(git.PullRequestParams) string); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(git.PullRequestParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGithubSvcProvider_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockGithubSvcProvider_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - params git.PullRequestParams
func (_e *MockGithubSvcProvider_Expecter) CreatePullRequest(params interface{}) *MockGithubSvcProvider_CreatePullRequest_Call {
	return &MockGithubSvcProvider_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", params)}
}

func (_c *MockGithubSvcProvider_CreatePullRequest_Call) Run(run func(params git.PullRequestParams)) *MockGithubSvcProvider_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(git.PullRequestParams))
	})
	return _c
}

func (_c *MockGithubSvcProvider_CreatePullRequest_Call) Return(_a0 string, _a1 error) *MockGithubSvcProvider_CreatePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGithubSvcProvider_CreatePullRequest_Call) RunAndReturn(run func(git.PullRequestParams) (string, error)) *MockGithubSvcProvider_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: repoUrl, repoIdentifier
func (_m *MockGithubSvcProvider) ValidateToken(repoUrl string, repoIdentifier string) (string, error) {
	ret := _m.Called(repoUrl, repoIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(repoUrl, repoIdentifier)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(repoUrl, repoIdentifier)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repoUrl, repoIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGithubSvcProvider_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockGithubSvcProvider_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - repoUrl string
//   - repoIdentifier string
func (_e *MockGithubSvcProvider_Expecter) ValidateToken(repoUrl interface{}, repoIdentifier interface{}) *MockGithubSvcProvider_ValidateToken_Call {
	return &MockGithubSvcProvider_ValidateToken_Call{Call: _e.mock.On("ValidateToken", repoUrl, repoIdentifier)}
}

func (_c *MockGithubSvcProvider_ValidateToken_Call) Run(run func(repoUrl string, repoIdentifier string)) *MockGithubSvcProvider_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGithubSvcProvider_ValidateToken_Call) Return(_a0 string, _a1 error) *MockGithubSvcProvider_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGithubSvcProvider_ValidateToken_Call) RunAndReturn(run func(string, string) (string, error)) *MockGithubSvcProvider_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGithubSvcProvider creates a new instance of MockGithubSvcProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGithubSvcProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGithubSvcProvider {
	mock := &MockGithubSvcProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
