// Code generated by mockery v2.53.2. DO NOT EDIT.

package remote_svc_provider_mocks

import (
	git "terraform-provider-tfmigrate/internal/util/vcs/git"

	mock "github.com/stretchr/testify/mock"
)

// MockGitlabSvcProvider is an autogenerated mock type for the GitlabSvcProvider type
type MockGitlabSvcProvider struct {
	mock.Mock
}

type MockGitlabSvcProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGitlabSvcProvider) EXPECT() *MockGitlabSvcProvider_Expecter {
	return &MockGitlabSvcProvider_Expecter{mock: &_m.Mock}
}

// CreatePullRequest provides a mock function with given fields: params
func (_m *MockGitlabSvcProvider) CreatePullRequest(params git.PullRequestParams) (string, error) {
	ret := _m.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for CreatePullRequest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(git.PullRequestParams) (string, error)); ok {
		return rf(params)
	}
	if rf, ok := ret.Get(0).(func(git.PullRequestParams) string); ok {
		r0 = rf(params)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(git.PullRequestParams) error); ok {
		r1 = rf(params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitlabSvcProvider_CreatePullRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePullRequest'
type MockGitlabSvcProvider_CreatePullRequest_Call struct {
	*mock.Call
}

// CreatePullRequest is a helper method to define mock.On call
//   - params git.PullRequestParams
func (_e *MockGitlabSvcProvider_Expecter) CreatePullRequest(params interface{}) *MockGitlabSvcProvider_CreatePullRequest_Call {
	return &MockGitlabSvcProvider_CreatePullRequest_Call{Call: _e.mock.On("CreatePullRequest", params)}
}

func (_c *MockGitlabSvcProvider_CreatePullRequest_Call) Run(run func(params git.PullRequestParams)) *MockGitlabSvcProvider_CreatePullRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(git.PullRequestParams))
	})
	return _c
}

func (_c *MockGitlabSvcProvider_CreatePullRequest_Call) Return(_a0 string, _a1 error) *MockGitlabSvcProvider_CreatePullRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitlabSvcProvider_CreatePullRequest_Call) RunAndReturn(run func(git.PullRequestParams) (string, error)) *MockGitlabSvcProvider_CreatePullRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: repoUrl, repoIdentifier, tokenFromProvider
func (_m *MockGitlabSvcProvider) ValidateToken(repoUrl string, repoIdentifier string, tokenFromProvider string) (string, error) {
	ret := _m.Called(repoUrl, repoIdentifier, tokenFromProvider)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return rf(repoUrl, repoIdentifier, tokenFromProvider)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(repoUrl, repoIdentifier, tokenFromProvider)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(repoUrl, repoIdentifier, tokenFromProvider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGitlabSvcProvider_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockGitlabSvcProvider_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - repoUrl string
//   - repoIdentifier string
//   - tokenFromProvider string
func (_e *MockGitlabSvcProvider_Expecter) ValidateToken(repoUrl interface{}, repoIdentifier interface{}, tokenFromProvider interface{}) *MockGitlabSvcProvider_ValidateToken_Call {
	return &MockGitlabSvcProvider_ValidateToken_Call{Call: _e.mock.On("ValidateToken", repoUrl, repoIdentifier, tokenFromProvider)}
}

func (_c *MockGitlabSvcProvider_ValidateToken_Call) Run(run func(repoUrl string, repoIdentifier string, tokenFromProvider string)) *MockGitlabSvcProvider_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockGitlabSvcProvider_ValidateToken_Call) Return(_a0 string, _a1 error) *MockGitlabSvcProvider_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGitlabSvcProvider_ValidateToken_Call) RunAndReturn(run func(string, string, string) (string, error)) *MockGitlabSvcProvider_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGitlabSvcProvider creates a new instance of MockGitlabSvcProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGitlabSvcProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGitlabSvcProvider {
	mock := &MockGitlabSvcProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
