with-expecter: true
issue-845-fix: true
packages:
  terraform-provider-tfmigrate/internal/util/vcs/git/remote_svc_provider:
    config:
      dir: "_mocks/util_mocks/vcs_mocks/git_mocks/remote_svc_provider_mocks"
      outpkg: "remote_svc_provider_mocks"
    interfaces:
      GithubSvcProvider:
      GitlabSvcProvider:
      BitbucketSvcProvider:
      RemoteVcsSvcProvider:
      RemoteVcsSvcProviderFactory:
  terraform-provider-tfmigrate/internal/util/vcs/git:
    config:
      dir: "_mocks/util_mocks/vcs_mocks/git_mocks"
      outpkg: "git_mocks"
    interfaces:
      GithubUtil:
      GitlabUtil:
      BitbucketUtil:
      GitUtil:
  terraform-provider-tfmigrate/internal/gitops:
    config:
      dir: "_mocks/helper_mocks/gitops_mocks"
      outpkg: "gitops_mocks"
    interfaces:
      GitOperations:
  terraform-provider-tfmigrate/internal/helper:
    config:
      dir: "_mocks/helper_mocks"
      outpkg: "helper_mocks"
    interfaces:
      TfStateOperations:
  terraform-provider-tfmigrate/internal/util/tfe:
    config:
      dir: "_mocks/util_mocks/tfe_mocks"
      outpkg: "tfe_mocks"
    interfaces:
      TfeUtil:
  terraform-provider-tfmigrate/internal/util/net:
    config:
      dir: "_mocks/net_mocks"
      outpkg: "net_mocks"
    interfaces:
      Client:
  terraform-provider-tfmigrate/internal:
    config:
      dir: "_mocks"
      outpkg: "mocks"
    interfaces:
      StackMigrationHashService:
  github.com/go-git/go-git/v5/plumbing/storer:
    config:
      dir: "_mocks/helper_mocks/iter_mocks"
      outpkg: "iter_mocks"
    interfaces:
      ReferenceIter:

