// Code generated by mockery v2.49.0. DO NOT EDIT.

package token_validator_mocks

import mock "github.com/stretchr/testify/mock"

// MockGithubTokenValidator is an autogenerated mock type for the GithubTokenValidator type
type MockGithubTokenValidator struct {
	mock.Mock
}

type MockGithubTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGithubTokenValidator) EXPECT() *MockGithubTokenValidator_Expecter {
	return &MockGithubTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateToken provides a mock function with given fields: repoUrl, repoIdentifier
func (_m *MockGithubTokenValidator) ValidateToken(repoUrl string, repoIdentifier string) (string, error) {
	ret := _m.Called(repoUrl, repoIdentifier)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(repoUrl, repoIdentifier)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(repoUrl, repoIdentifier)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(repoUrl, repoIdentifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGithubTokenValidator_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type MockGithubTokenValidator_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - repoUrl string
//   - repoIdentifier string
func (_e *MockGithubTokenValidator_Expecter) ValidateToken(repoUrl interface{}, repoIdentifier interface{}) *MockGithubTokenValidator_ValidateToken_Call {
	return &MockGithubTokenValidator_ValidateToken_Call{Call: _e.mock.On("ValidateToken", repoUrl, repoIdentifier)}
}

func (_c *MockGithubTokenValidator_ValidateToken_Call) Run(run func(repoUrl string, repoIdentifier string)) *MockGithubTokenValidator_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockGithubTokenValidator_ValidateToken_Call) Return(_a0 string, _a1 error) *MockGithubTokenValidator_ValidateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGithubTokenValidator_ValidateToken_Call) RunAndReturn(run func(string, string) (string, error)) *MockGithubTokenValidator_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGithubTokenValidator creates a new instance of MockGithubTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGithubTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGithubTokenValidator {
	mock := &MockGithubTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
